export const HIT_DAMAGE = 'HIT_DAMAGE';
export const CHANGE_NAME = 'CHANGE_NAME';
export const CREATE_CHARACTER = 'CREATE_CHARACTER';
export const INCREMENT_STAT = 'INCREMENT_STAT';
export const DECREMENT_STAT = 'DECREMENT_STAT';
export const FAILED = "FAILED";